name: image_editor_app
description: A Flutter image editing application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 이미지 처리
  image_picker: ^1.0.4
  image: ^4.1.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  image_cropper: ^5.0.0
  photo_view: ^0.14.0
  
  # 파일 공유
  share_plus: ^7.2.1
  
  # 디바이스 정보
  device_info_plus: ^9.1.1
  
  # 상태 관리
  provider: ^6.1.1
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
